spring:
  application:
    name: single-provider
server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://libin1:8762/eureka/,http://libin:8763/eureka/