spring:
  application:
#    name: erueka-provider-outside
    name: erueka-provider-inner
server:
  port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8762/eureka/,http://localhost:8761/eureka/
