server:
  port: 8762

eureka:
  instance:
    hostname: libin
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/