server:
  port: 10001
spring:
  application:
    name: dubbo-consumer
logging:
  level:
    druid:
      sql:
        Statement: debug
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    id: dubbo-provider
    name: dubbo-provider
